apiVersion: v1
kind: Service
metadata:
  name: deployment-service-node
  namespace: homework-4
spec:
  ports:
    - name: http-app
      port:  80
      nodePort: 30000
    - name: http-mult
      port:  8080
      nodePort: 30001
  selector:
    app: main
  type: NodePort