apiVersion: v1
kind: Service
metadata: 
  name: deploy-service-nginx
  namespace: homework-4
  labels:
    app: main
spec: 
  ports:
    - name: http-nginx
      port: 9001
      protocol: TCP
      targetPort: 80
    - name: http-mult
      port: 9002
      protocol: TCP
      targetPort: 8080
  selector: 
    app: main

